---
env:
  browser: true
  node: true
  es6: true
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  requireConfigFile: false
  sourceType: script
plugins:
  - prettier
  - sonarjs
  - unicorn
  - github
  - html
extends:
  - eslint:recommended
  - plugin:github/recommended
  - plugin:sonarjs/recommended
  - plugin:unicorn/recommended
  - prettier
  - plugin:prettier/recommended
rules:
  prettier/prettier:
    - warn
    - {}
    - usePrettierrc: true
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  one-var-declaration-per-line:
    - error
    - always
