---
extends:
- stylelint-config-wikimedia/support-modern
- stylelint-config-standard
rules:
  indentation: tab
  function-disallowed-list:
  declaration-property-unit-disallowed-list:
  color-named:
  max-empty-lines:
  selector-max-id:
  function-url-quotes:
  declaration-property-value-disallowed-list:
  string-quotes: double
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-single-line-max-declarations: 1
  plugin/no-unsupported-browser-features:
  declaration-colon-space-before:
  unit-disallowed-list:
